epuck
(
  name "r0"
  pose [ -1 -1 0 45.000 ]
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(     
  name "r1"
  pose [ -0.5 -1 0 45.000 ] 
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(     
  name "r2"
  pose [ 0 -1 0 45.000 ] 
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(     
  name "r3"
  pose [ 0.5 -1 0 45.000 ] 
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(     
  name "r4"
  pose [ 1 -1 0 45.000 ] 
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(     
  name "r5"
  pose [  1.5 -1 0 45.000 ] 
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(
  name "r6"
  pose [ -1 0 0 45.000 ]
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(     
  name "r7"
  pose [ -0.5 0 0 45.000 ] 
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(     
  name "r8"
  pose [ 0 0 0 45.000 ] 
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(     
  name "r9"
  pose [ 0.5 0 0 45.000 ] 
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(     
  name "r10"
  pose [ -1.5 0 0 45.000 ] 
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)

epuck
(     
  name "r11"
  pose [  -2 0 0 45.000 ] 
  localization "gps"
  localization_origin [ 0 0 0 0 ]
)